# Which base image to use for the container python
FROM python:3.7

#Copy "." means all the files to the working directory of the container
COPY . /app

# Set the working directory to /app
WORKDIR /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 5000 or any port available in the server available to the world outside this container
EXPOSE $PORT 

# Run app.py when the container launches
CMD ["python", "app.py"]